### ISSUE TITLE
졸업설계 11주차 진행

### ISSUE THREAD

**Issue by eunseo-kim** [limitless-study/QuizMap-frontend#33]
## TODO
- [x] 학습하기 화면에서 "현재 카드가 속한 카드셋 이름"을 상단에 보여주기
- [x] 데드라인 기능 보완
- [x] 별점 기능 추가하기
- [x] BreadCrumbs UI 수정 (Notion UI 참고)
- [x] /learn 페이지에서 답안을 임시로 작성해보는 notes 구현하기
- [ ] 회원가입 구현
- [ ] 카드 순서 조정 기능
- [ ] 카드 뒤집히는 효과
- [ ] 학습 시 `learningSeconds` 계산해서 백엔드에 넘기기

---

- [x] components 폴더 분리하기 ([velog-client 구조 참고하기](https://github.com/velopert/velog-client/tree/master/src/components))

---

### 별점 기능
- [x]  X or O 누르는 순간에 (만약 starCount가 바뀐 경우) starCount PATCH로 넘기기
- 단, learningCards는 처음에 딱 한번 가져오므로, 바뀐 starCount 값은 frontend 쪽에서 임시로 저장하고 있어야 함.
  - ex. 'X'를 누르면 카드를 맨 뒤에 다시 추가하는 방식이므로,
  - 카드의 starCount를 바꾸고 'X'를 눌러서 이후에 해당 카드를 다시 보는 경우,
  - 바꿨던 starCount가 그대로 적용되어 있어야 함

**Comment by eunseo-kim** [comment]
- studio 페이지에서 현재 카드 삭제 시 editor 안 바뀜
